<a href="https://colab.research.google.com/github/diegonalvarez/machine-learning-group/blob/master/mapa_pycountry_coronavirus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%load_ext google.colab.data_table

In [0]:
import pandas as pd
df = pd.read_csv('totalescv.csv')
df.head(5)

FileNotFoundError: ignored

In [0]:
df = df.T
df

                        0           1   ...          52          53
date            2020-01-21  2020-01-22  ...  2020-03-13  2020-03-14
World                  282         314  ...      132758      142539
Afghanistan            NaN         NaN  ...           7           7
Albania                NaN         NaN  ...          23          33
Algeria                NaN         NaN  ...          25          26
...                    ...         ...  ...         ...         ...
United Kingdom         NaN         NaN  ...         594         802
United States          NaN         NaN  ...        1264        1678
Vatican                NaN         NaN  ...           1           1
Venezuela              NaN         NaN  ...         NaN           2
Vietnam                NaN         NaN  ...          39          48

[138 rows x 54 columns]

In [0]:
df = df.drop(['date'])
df

                 0    1    2    3   ...      50      51      52      53
World           282  314  581  846  ...  118319  125260  132758  142539
Afghanistan     NaN  NaN  NaN  NaN  ...       4       7       7       7
Albania         NaN  NaN  NaN  NaN  ...      10      10      23      33
Algeria         NaN  NaN  NaN  NaN  ...      20      25      25      26
Andorra         NaN  NaN  NaN  NaN  ...       1       1       1       2
...             ...  ...  ...  ...  ...     ...     ...     ...     ...
United Kingdom  NaN  NaN  NaN  NaN  ...     373     460     594     802
United States   NaN  NaN    1    1  ...     696     987    1264    1678
Vatican         NaN  NaN  NaN  NaN  ...       1       1       1       1
Venezuela       NaN  NaN  NaN  NaN  ...     NaN     NaN     NaN       2
Vietnam         NaN  NaN  NaN    2  ...      35      39      39      48

[137 rows x 54 columns]

In [0]:
df = df.reset_index()
df

              index    0    1    2    3  ...      49      50      51      52      53
0             World  282  314  581  846  ...  113702  118319  125260  132758  142539
1       Afghanistan  NaN  NaN  NaN  NaN  ...       4       4       7       7       7
2           Albania  NaN  NaN  NaN  NaN  ...       2      10      10      23      33
3           Algeria  NaN  NaN  NaN  NaN  ...      20      20      25      25      26
4           Andorra  NaN  NaN  NaN  NaN  ...       1       1       1       1       2
..              ...  ...  ...  ...  ...  ...     ...     ...     ...     ...     ...
132  United Kingdom  NaN  NaN  NaN  NaN  ...     323     373     460     594     802
133   United States  NaN  NaN    1    1  ...     472     696     987    1264    1678
134         Vatican  NaN  NaN  NaN  NaN  ...       1       1       1       1       1
135       Venezuela  NaN  NaN  NaN  NaN  ...     NaN     NaN     NaN     NaN       2
136         Vietnam  NaN  NaN  NaN    2  ...      31      35      39      39      48

[137 rows x 55 columns]

In [0]:
print(list(df)) #para ver los nombres de todas las columnas

['index', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53]

In [0]:
df = df.rename({'index':'paises',
                53:'total'},axis=1)
df

             paises    0    1    2    3  ...      49      50      51      52   total
0             World  282  314  581  846  ...  113702  118319  125260  132758  142539
1       Afghanistan  NaN  NaN  NaN  NaN  ...       4       4       7       7       7
2           Albania  NaN  NaN  NaN  NaN  ...       2      10      10      23      33
3           Algeria  NaN  NaN  NaN  NaN  ...      20      20      25      25      26
4           Andorra  NaN  NaN  NaN  NaN  ...       1       1       1       1       2
..              ...  ...  ...  ...  ...  ...     ...     ...     ...     ...     ...
132  United Kingdom  NaN  NaN  NaN  NaN  ...     323     373     460     594     802
133   United States  NaN  NaN    1    1  ...     472     696     987    1264    1678
134         Vatican  NaN  NaN  NaN  NaN  ...       1       1       1       1       1
135       Venezuela  NaN  NaN  NaN  NaN  ...     NaN     NaN     NaN     NaN       2
136         Vietnam  NaN  NaN  NaN    2  ...      31      35      39      39      48

[137 rows x 55 columns]

In [0]:
!pip install pycountry

Collecting pycountry
  Downloading https://files.pythonhosted.org/packages/16/b6/154fe93072051d8ce7bf197690957b6d0ac9a21d51c9a1d05bd7c6fdb16f/pycountry-19.8.18.tar.gz (10.0MB)
     |████████████████████████████████| 10.0MB 2.9MB/s
Building wheels for collected packages: pycountry
  Building wheel for pycountry (setup.py) ... done
  Created wheel for pycountry: filename=pycountry-19.8.18-py2.py3-none-any.whl size=10627361 sha256=84bfcedbb77544a205e0baa93a6b94e28ecdbbfcbf2352107812fde8e02ca2ab
  Stored in directory: /root/.cache/pip/wheels/a2/98/bf/f0fa1c6bf8cf2cbdb750d583f84be51c2cd8272460b8b36bd3
Successfully built pycountry
Installing collected packages: pycountry
Successfully installed pycountry-19.8.18

In [0]:
import pycountry
def get_alpha_3(location):
  try:
    return pycountry.countries.get(name=location).alpha_3
  except:
    return None
df['Code'] = df['paises'].apply(lambda x: get_alpha_3(x))
df

             paises    0    1    2    3  ...      50      51      52   total  Code
0             World  282  314  581  846  ...  118319  125260  132758  142539  None
1       Afghanistan  NaN  NaN  NaN  NaN  ...       4       7       7       7   AFG
2           Albania  NaN  NaN  NaN  NaN  ...      10      10      23      33   ALB
3           Algeria  NaN  NaN  NaN  NaN  ...      20      25      25      26   DZA
4           Andorra  NaN  NaN  NaN  NaN  ...       1       1       1       2   AND
..              ...  ...  ...  ...  ...  ...     ...     ...     ...     ...   ...
132  United Kingdom  NaN  NaN  NaN  NaN  ...     373     460     594     802   GBR
133   United States  NaN  NaN    1    1  ...     696     987    1264    1678   USA
134         Vatican  NaN  NaN  NaN  NaN  ...       1       1       1       1  None
135       Venezuela  NaN  NaN  NaN  NaN  ...     NaN     NaN     NaN       2  None
136         Vietnam  NaN  NaN  NaN    2  ...      35      39      39      48  None

[137 rows x 56 columns]

In [0]:
#print(get_alpha_3('Venezuela'))
print(pycountry.countries.get(name='Germany').alpha_3)

DEU

In [0]:
df[df['Code'] == 'None'].count()

paises    0
0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
28        0
29        0
30        0
31        0
32        0
33        0
34        0
35        0
36        0
37        0
38        0
39        0
40        0
41        0
42        0
43        0
44        0
45        0
46        0
47        0
48        0
49        0
50        0
51        0
52        0
total     0
Code      0
dtype: int64

In [0]:
import plotly.express as px

In [0]:
fig = px.choropleth(df,locations='Code',
                     color='total', hover_name='paises',
                     color_continuous_scale = px.colors.sequential.Plasma)
fig.show()